### ISSUE TITLE
Compatibility with TYPO3 9.5 

### ISSUE THREAD

**Issue by SvenJuergens** [portrino/px_semantic#4]
hi,

I think you have built a great extension there, thank you so much.
Do you also plan a compatible version with TYPO3 9.5?

best regards
Sven

**Comment by EvilBMP** [comment]
Sorry, this is not scheduled for this year anymore, but I think it's on the list for the first quarter of 2019. Nevertheless you're free to fork, test and provide issues or pull requests.

Regards,
Axel

**Comment by SvenJuergens** [comment]
hi, thanks for your feedback and sorry if it sounded as if I said could you release a 9.5 version today :)

Was rather the general question if you continue to support the project :)

Best Regards
Sven

**Comment by EvilBMP** [comment]
It wasn't offending - I just wanted to say, that we currently have no v9 project where this plugin is needed. That's why I mentioned, that you are free to fork the extension and test it already for yourself. Feel free to open issues or pull-requests if you find any incompatibilities.
